// Code generated by "stringer -type=RenderFormat"; DO NOT EDIT.

package termrender

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatDefault-0]
	_ = x[FormatJSON-1]
	_ = x[FormatJSONLines-2]
	_ = x[FormatCSV-3]
	_ = x[FormatTable-4]
	_ = x[FormatYML-5]
	_ = x[FormatXML-6]
}

const _RenderFormat_name = "FormatDefaultFormatJSONFormatJSONLinesFormatCSVFormatTableFormatYMLFormatXML"

var _RenderFormat_index = [...]uint8{0, 13, 23, 38, 47, 58, 67, 76}

func (i RenderFormat) String() string {
	if i < 0 || i >= RenderFormat(len(_RenderFormat_index)-1) {
		return "RenderFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RenderFormat_name[_RenderFormat_index[i]:_RenderFormat_index[i+1]]
}
